### ISSUE TITLE
Smartshades plugin no longer seems to work at all

### ISSUE THREAD

**Issue by Mattserati** [jvmahon/smartshades#12]
After updating to iOS15.4,I can't get HomeKit to operate any of my blinds at all - neither through voice control, nor manual operation of the HomeKit controls.
Everything worked previously, so not sure exactly what's wrong.
Operating just fine through the NEO Smartshades app

**Comment by jvmahon** [comment]
Yeah, there are a number of issues in iOS 15.4 with control of blinds. Its not just this plugin - I've seen issues posted that Home Assistant is also having trouble with its plugins for shade control.  

But, the issues I've seen are limited to voice, not the iOS app.

Try rebooting HomeBridge to see if it helps.

**Comment by jvmahon** [comment]
iOS update 15.4.1 was just released and fixes the Siri shade control issue. Try updating your iOS devices, including Apple TVs, then restart your shade controller followed by your homebridge computer.

Re-open this issue if you are still having problems after doing the above.

**Comment by Mattserati** [comment]
I have updated everything, but still having issues.
I have noticed two changes in the config for the plugin:

1. When putting the url of the controller in, the plugin seems to insist on an http format (screenshot below). My previous 192.168.1.200 always worked before.

<img width="739" alt="Screen Shot 2022-04-01 at 9 38 25 am" src="https://user-images.githubusercontent.com/35052287/161178204-d7f1e5f2-5081-4e7a-bb62-450f8f7474b4.png">

2. There are now motor selections to choose from - I have no idea what sort of motor my cafe blinds use. Can you suggest a generic one that will work?

**Comment by jvmahon** [comment]
Are you using the latest version v1.0.1?  If not, please update.

The text under your IP entry box is odd - it should look like what I've pasted below

![image](https://user-images.githubusercontent.com/15061942/161180205-c1841ff3-9265-4c02-adbd-00083094bc64.png)

A common motor is the "BoFu - standard motor", but you might have to try them all to get it right.

**Comment by Mattserati** [comment]
Using v1.0.1
That text is there until I tab out of the box, and then changes to what I have screenshot
Still not seeing any action, no matter what motor is selected

**Comment by jvmahon** [comment]
This is very puzzling.
Can you check the IP of the NEO controller. Maybe it changed?

**Comment by Mattserati** [comment]
![Uploading 6AF25D54-2A1D-486D-9678-E34A22D0E5B8.png…]()

**Comment by Mattserati** [comment]
![IMG_6416](https://user-images.githubusercontent.com/35052287/161241623-5a3ff905-de72-44cf-966e-aa1e53b9b9ef.PNG)

**Comment by Mattserati** [comment]
To be clear, the setting for IP I have entered is 192.168.1.200

**Comment by Mattserati** [comment]
<img width="746" alt="Screen Shot 2022-04-01 at 6 01 08 pm" src="https://user-images.githubusercontent.com/35052287/161241983-4fd88c11-2e08-48ed-b07a-c79112acbe33.png">

**Comment by jvmahon** [comment]
Are you running on a Raspberry Pi? Or what platform?

Go to Homebridge Settings and enable "Insecure" mode as well as Avahi as the mDNS Advertiser, then restart homebridge

![image](https://user-images.githubusercontent.com/15061942/161242582-0cf91973-b21b-43e5-b41c-4bd620035437.png)

**Comment by jvmahon** [comment]
After the restart, go to the Homebridge "Accessories" tab:
![image](https://user-images.githubusercontent.com/15061942/161242945-4b377e83-a5b7-40ee-9cfa-4557246ba88b.png)

**Comment by jvmahon** [comment]
After you click on "Accessories", you should see all your Homebridge accessories.

Do you see your shade?

Try controlling the shade from that tab - does it work?

**Comment by jvmahon** [comment]
> To be clear, the setting for IP I have entered is 192.168.1.200

Yes, that looks correct.

**Comment by Mattserati** [comment]
Setting changes made. Restarted. 
still no action.

**Comment by jvmahon** [comment]
You mentioned this as a "Cafe" motor. Do you have a link to its manufacturer / specs?  Is there a label on the motor you could show?

The only thing I can suggest is to completely delete the plugin, re-install, and try again fresh.  I'm completely puzzled by this.

**Comment by Mattserati** [comment]
Not really. Everything was built into a shroud, which I can’t really remove. 
m it everything was also working until 2 days ago, and the NeoSmartShades app still operates everything just fine.

**Comment by Mattserati** [comment]
I even tried uninstalling and reinstalling the plugin today, with no success.

**Comment by jvmahon** [comment]
In your NEO App, go tot he page for that particular shade. 

At the bottom of that page, you should see your Motor Code. Can you confirm the code and confirm that you are using the correct blind code. See below 


![image](https://user-images.githubusercontent.com/15061942/161245607-f1b7c2be-6119-4ca0-b1a9-ca0b43186e80.png)

**Comment by jvmahon** [comment]
I just published an updated plugin 1.0.4 which more clearly shows the motor code that is being selected in the plugin's dropdown.

**Comment by Mattserati** [comment]
They are WT. 
I have changed that for each, and updated the plug-in……and everything is back working!

thanks for your help

**Comment by jvmahon** [comment]
> They are WT. I have changed that for each, and updated the plug-in……and everything is back working!
> 
> thanks for your help

You're welcome.  Glad this is now fixed.
