### ISSUE TITLE
Add Favorite Setting Capability?

### ISSUE THREAD

**Issue by knedd** [jvmahon/smartshades#13]
As you know, there is another version of this app "homebridge-neosmarshades" that includes the ability to leverage a favorite setting, which has default at 25%. Unfortunately the "homebridge-neosmartshades" app was published two years ago has a major error that will not allow it to load within Homebridge.  

Would it be possible to add the "favorite" capability to this more recent version of "homebridge-smartshades" app as well?  I use the "favorite" function to close blinds that are already in the down position.  

This would be very helpful and greatly appreciated.

**Comment by jvmahon** [comment]
I think so. Some questions.

In your experience, is it hard to exactly "hit" the 25%?  I.e., should I have a range like 15-35% so the user doesn't have to be so precise with the slider.

Does it make sense to also do this around the 75% range?  I.e., anything between 65-85% also sets to the "favorite"

**Comment by knedd** [comment]
Thanks for taking this on.  

For me, hitting an exact percentage has not been an issue as Homekit presents a slider for shades.  However, I do like the idea of a range, which would make it easier. Perhaps something like 90-95%, as the opening of the blind occurs just before it is completely lowered?

**Comment by knedd** [comment]
Were my answers helpful?

**Comment by jvmahon** [comment]
Yes.  As an update - I plan to revise the code so that you can enable or disable a "favorites" feature on a per-device basis.  I'm also revising so that if one uses a "no" code motor, you can get a "true"   0 - 100% setting (its the only one of the NEO-supported motors that allows this. I've started working on the updates, but  it will probably be a week or so before I get this done (quite busy with my 'real' job at the moment.).

**Comment by knedd** [comment]
This will be a great update.  Thank you very much for your efforts!

**Comment by kmnedd** [comment]
Any progress on your update?

**Comment by knedd** [comment]
Any progress on your update?

**Comment by jvmahon** [comment]
No. It may be a while - my "real" work is keeping me too busy to look at this right now.

**Comment by knedd** [comment]
Is this still on your radar?

**Comment by knedd** [comment]
Sorry to bother you again, but do you still plan on doing this?

**Comment by jvmahon** [comment]
I've kept this comment open with the plan that I'll eventually get it done (I generally keep comments open until I make a final fix / no-go decision). Unfortunately, work has been several months of too busy schedules, so I can't predict when.

**Comment by jvmahon** [comment]
I've published it as a beta for you to test.

To install the Beta,
1. From the Config-ui-x interface, select ...
2. 
![image](https://user-images.githubusercontent.com/15061942/198256750-6584976a-25b2-4458-96d7-0a6ecfe1ae00.png)

Then select the beta version

![image](https://user-images.githubusercontent.com/15061942/198257232-077f3942-9a97-456d-8cc9-b0d3676950b1.png)


I haven't had time to test this, so please let me know if it works.

**Comment by kmnedd** [comment]
Thank you!  What setting is required to enable a favorite?KevinSent via iPhoneOn Oct 27, 2022, at 06:10, jvmahon ***@***.***> wrote:﻿
I've published it as a beta for you to test.
To install the Beta,

From the Config-ui-x interface, select ...



Then select the beta version

I haven't had time to test this, so please let me know if it works.

**Comment by kmnedd** [comment]
I tested the beta and it works like a charm! The favorite feature works as we discussed. KevinSent via iPhoneOn Oct 27, 2022, at 06:10, jvmahon ***@***.***> wrote:﻿
I've published it as a beta for you to test.
To install the Beta,

From the Config-ui-x interface, select ...



Then select the beta version

I haven't had time to test this, so please let me know if it works.

**Comment by jvmahon** [comment]
Thanks for testing. Its now published as a "regular" version (1.0.7)

**Comment by EdrinP** [comment]
Thanks for adding the favorite feature! I've also tested this with 1.0.7.

One observation:  If asking Siri to "set the blind to 25%", it works great and moves to the Favorite position (as specified in Neo app for each shade).

If instead we drag the slider in the Home app accessory detail view (long-press the tile) it is not as precise -- shade starts moving a bit as we get closer to 25% then stops moving. Does not go to favorite position.   I see you're using only 24-26% range, and maybe increasing it a bit (20-30?) may help. Not a big deal as I'd rarely use the slider, in favor of Siri or automations to ask for exactly 25%.
