### ISSUE TITLE
Won't control my blinds.

### ISSUE THREAD

**Issue by d2too** [jvmahon/smartshades#14]
Hi,
Just trying to setup your plugin but it appears to be ok in the log under hoops but it won't control the blinds.
here is my script below. 
I was wondering if the device id was incorrect as its looking a different format to what you show but what I have put in is what I see under controllers in the app.
many thanks,
Dave.

    "platform": "NEOShades",
    "name": "NEOShades",
    "host": "192.168.7.129",
    "controllerID": "N8Yq-N7AW_aUgPx8zIJmyw",
    "shades": [
        {
            "name": "Landing",
            "code": "068.058-01"
        },
        {
            "name": "Hall",
            "code": "081.174.01"
        }
    ]
}

**Comment by j-leist** [comment]
Same issue here with mine unfortunately

**Comment by j-leist** [comment]
@d2too I had the same problem and found the solution...

In the app is a motor code, in my case it was K2, add this to your config like so...

```
{
    "platform": "NEOShades",
    "name": "NEOShades",
    "host": "192.168.0.103",
    "controllerID": "XXXXXXXXXX",
    "shades": [
        {
            "name": "Right",
            "code": "216.020-02",
            "motorType": "k2"
        },
        {
            "name": "Centre",
            "code": "216.020-03",
            "motorType": "k2"
        },
        {
            "name": "Left",
            "code": "216.020-04",
            "motorType": "k2"
        }
    ]
}
```

**Comment by jvmahon** [comment]
Is it a NEO controller?  Are you configuring using the Config-UI-X interface?
The newest NEO controllers support a range of different shade motor brands, and you now have to also indicate which brand of motor.

The Config-UI-X interface now allows you to select the motor type -- you may need to do taht.

Also, I note that the "code" in your entry has two different formats -- one with dashes, one without.

**Comment by jvmahon** [comment]
I was just responding when the prior post was made.

Use the Config-UI-X interface and select the motor type.

The newest controllers work with different motor types and you have to select the correct one from the config-ui-x interface.

**Comment by jvmahon** [comment]
Also, note the code format. For your "Hall" shade, the format is different from your Landing shade.

**Comment by j-leist** [comment]
@jvmahon That is actually how I found it, I am using Hoobs. Oddly though I don't get the dropdown, I did some updates which in turn showed the dropdown though it is no longer visible so I just added manually to the config which seems to have worked fine now.

Either way all good :)

**Comment by d2too** [comment]
Thank you for the response.
I never got an email alert so didn't know there were any responses till you closed this.
They now work, thankyou.
They now fully open or fully close. My blinds have one setting inbetween that is partially closed as well. 
Can that be operated from the homekit app?

Regards
Dave.
