### ISSUE TITLE
Ability to add stop, upper limit and lower limit control?

### ISSUE THREAD

**Issue by ievolk** [jvmahon/smartshades#16]
Hi there! First off, thank you so much for this plug-in it works great with my neo controller and blinds. 

Was just curious if there was a way you could add some other button options. 

Would it be possible to add like, setting blind percentage at 50% would send a stop command. Setting at 75% would send an up limit. And 25% would set down limit. 

Right now if I open my blind it will completely open and bypass all my intermediate limits I have set. 

Attached is a screenshot of my neo controller. There’s buttons for completely open and close. And then the open upper limits and close limits. And a stop command. 

So in theory I’d be able to set a smart remote to open and then have another button that would set it to 50% which could stop it at a certain point. 

thank you! 

![19DCECB2-B45B-4337-B7C6-08C9144DC5C8](https://user-images.githubusercontent.com/119266613/204165170-e9144f8d-4660-4b29-a65f-68d422ee6856.png)

**Comment by jvmahon** [comment]
See this issue:  https://github.com/jvmahon/homebridge-smartshades/issues/13
There's already a limited ability to do something like what you are asking.

Unfortunately, my "real" job keeps me quite busy so I won't have time to add any new features for a long while. My hope is that, now that the "Matter" standard has been released, Neo makes their controller Matter compatible and none of us will need this plugin! One can hope.
